version: '3.5'

services:

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin

  tempo:
    image: grafana/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ../deploy/grafana/tempo-local.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    ports:
      - 55680:55680
      - 3200:3200
  
  loki:
    image: grafana/loki
    volumes:
      - loki-data:/loki
    ports:
      - 3100:3100

  fluentd:
    image: grafana/fluent-plugin-loki:master
    command:
      - "fluentd"
      - "-v"
      - "-p"
      - "/fluentd/plugins"
    environment:
      LOKI_URL: http://loki:3100
      FLUENTD_CONF: docker.conf
    ports:
      - 24224:24224
    volumes:
      - ../deploy/grafana/fluentd-loki.conf:/fluentd/etc/docker.conf
    depends_on:
      - loki
  
  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus-data:/prometheus
      - ../deploy/grafana/prometheus.yaml:/etc/prometheus/prometheus.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 9090:9090
    user: root

  identity-api:
    environment:
      - ServiceName=identity-api
    logging:
      driver: fluentd
      options:
        fluentd-sub-second-precision: "true"
        env: ServiceName
    depends_on:
      - fluentd

  basket-api:
    environment:
      - ServiceName=basket-api
    logging:
      driver: fluentd
      options:
        fluentd-sub-second-precision: "true"
        env: ServiceName
    depends_on:
      - fluentd

  catalog-api:
    environment:
      - ServiceName=catalog-api
    logging:
      driver: fluentd
      options:
        fluentd-sub-second-precision: "true"
        env: ServiceName
    depends_on:
      - fluentd

  ordering-api:
    environment:
      - ServiceName=ordering-api
    logging:
      driver: fluentd
      options:
        fluentd-sub-second-precision: "true"
        env: ServiceName
    depends_on:
      - fluentd

  ordering-backgroundtasks:
    environment:
      - ServiceName=ordering-backgroundtasks
    logging:
      driver: fluentd
      options:
        fluentd-sub-second-precision: "true"
        env: ServiceName
    depends_on:
      - fluentd

  payment-api:
    environment:
      - ServiceName=payment-api
    logging:
      driver: fluentd
      options:
        fluentd-sub-second-precision: "true"
        env: ServiceName
    depends_on:
      - fluentd

  webshoppingagg:
    environment:
      - ServiceName=webshoppingagg
    logging:
      driver: fluentd
      options:
        fluentd-sub-second-precision: "true"
        env: ServiceName
    depends_on:
      - fluentd

  ordering-signalrhub:
    environment:
      - ServiceName=ordering-signalrhub
    logging:
      driver: fluentd
      options:
        fluentd-sub-second-precision: "true"
        env: ServiceName
    depends_on:
      - fluentd

  webspa:
    environment:
      - ServiceName=webspa
    logging:
      driver: fluentd
      options:
        fluentd-sub-second-precision: "true"
        env: ServiceName
    depends_on:
      - fluentd

  webmvc:
    environment:
      - ServiceName=webmvc
    labels:
      - "prometheus.enable=true"
    logging:
      driver: fluentd
      options:
        fluentd-sub-second-precision: "true"
        env: ServiceName
    depends_on:
      - fluentd

volumes:
  grafana-data:
    external: true
  elasticsearch-data:
    external: true
  tempo-data:
    external: true
  loki-data:
    external: true
  fluentd-data:
    external: true
  prometheus-data:
    external: true
